version: "3.6"

networks:
  inside:
    external: false

services:
  db:
    image: mariadb:10.2
    container_name: "ojs_db_${COMPOSE_PROJECT_NAME:-demo}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"
      MYSQL_DATABASE: "${OJS_DB_NAME:-ojs}"
      MYSQL_USER: "${OJS_DB_USER:-ojs}"
      MYSQL_PASSWORD: "${OJS_DB_PASSWORD:-ojsPwd}"
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/dump:/docker-entrypoint-initdb.d
    networks:
      - inside
    restart: always

  ojs:
    image: "pkpofficial/${OJS_IMAGE:-ojs}:${OJS_VERSION:-latest}"
    container_name: "ojs_app_${COMPOSE_PROJECT_NAME:-demo}"
    hostname: "${COMPOSE_PROJECT_NAME:-demo}"
    ports:
      - "${HTTP_PORT:-8081}:80"
      - "${HTTPS_PORT:-8443}:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/private:/var/www/files
      - ./volumes/public:/var/www/html/public
      # Corrigé : Montage d'un fichier vers un chemin valide dans le conteneur
      - ./volumes/config/ojs.config.inc.php:/var/www/html/config/ojs.config.inc.php
    networks:
      - inside
    depends_on:
      - db
    restart: always

  proxy:
    image: nginx:alpine
    container_name: "ojs_proxy_${COMPOSE_PROJECT_NAME:-demo}"
    ports:
      - "8080:80" # Proxy pour rediriger vers ojs
    volumes:
      - ./volumes/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - inside
    depends_on:
      - ojs
    restart: always
